apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hvsdv3sct-go
  janus-idp.io/tekton: hvsdv3sct-go
  backstage.io/kubernetes-id: hvsdv3sct-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hvsdv3sct-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
