apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hvsdv3sct-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hvsdv3sct-go 
  name: hvsdv3sct-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hvsdv3sct-go 
